import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

from app import main as main_module
from app.main import app
from app.config import settings


# ============================================================
# CONFIG
# ============================================================

CAMERA_ID = 1
TEST_IMAGE = Path("tests/sample.jpg")

PROJECT_DIR = (
    Path(__file__)
    .resolve()
    .parent
    .parent
)

ORIGINAL_DIR = (
    PROJECT_DIR
    / "images"
    / "original"
)

RESULT_DIR = (
    PROJECT_DIR
    / "images"
    / "result"
)


# ============================================================
# TEST CLIENT
# ============================================================

client = TestClient(
    app,
    raise_server_exceptions=False,
)


# ============================================================
# DATABASE
# ============================================================

engine = create_engine(
    settings.database_url
)


# ============================================================
# HELPERS
# ============================================================

def post_detect():
    """
    Send detection request using the real API.
    """

    with open(
        TEST_IMAGE,
        "rb",
    ) as f:

        return client.post(
            "/api/v1/detect",
            params={
                "camera_id": CAMERA_ID,
            },
            files={
                "image": (
                    "recovery_audit.jpg",
                    f,
                    "image/jpeg",
                )
            },
        )


def get_latest_image_id():
    """
    Get latest image_id created by the test.
    """

    with engine.connect() as connection:

        result = connection.execute(
            text(
                """
                SELECT image_id
                FROM belt.image
                ORDER BY image_id DESC
                LIMIT 1
                """
            )
        )

        row = result.fetchone()

    if row is None:
        return None

    return row[0]


def get_image_record(
    image_id,
):
    """
    Read image record directly from PostgreSQL.
    """

    with engine.connect() as connection:

        result = connection.execute(
            text(
                """
                SELECT
                    image_id,
                    filename,
                    image_path,
                    result_path,
                    status,
                    processed_time,
                    inference_time_ms
                FROM belt.image
                WHERE image_id = :image_id
                """
            ),
            {
                "image_id": image_id
            },
        )

        row = result.mappings().first()

    if row is None:
        return None

    return dict(row)


def count_detections(
    image_id,
):
    """
    Count detections belonging to image.
    """

    with engine.connect() as connection:

        result = connection.execute(
            text(
                """
                SELECT COUNT(*)
                FROM belt.detection
                WHERE image_id = :image_id
                """
            ),
            {
                "image_id": image_id
            },
        )

        return result.scalar()


def count_inspection_results(
    image_id,
):
    """
    Count inspection results belonging to image.
    """

    with engine.connect() as connection:

        result = connection.execute(
            text(
                """
                SELECT COUNT(*)
                FROM belt.inspection_result
                WHERE image_id = :image_id
                """
            ),
            {
                "image_id": image_id
            },
        )

        return result.scalar()


def find_files_for_image(
    image_id,
):
    """
    Find files generated for this image_id.
    """

    original_files = list(
        ORIGINAL_DIR.glob(
            f"{image_id}_*"
        )
    )

    result_files = list(
        RESULT_DIR.glob(
            f"{image_id}_*"
        )
    )

    return (
        original_files,
        result_files,
    )


def cleanup_image_files(
    image_id,
):
    """
    Remove files generated by the audit.
    """

    original_files, result_files = (
        find_files_for_image(
            image_id
        )
    )

    for file_path in (
        original_files
        + result_files
    ):

        try:

            file_path.unlink(
                missing_ok=True
            )

        except Exception:

            pass


# ============================================================
# REC-01
# DB TRANSACTION FAILURE
# ============================================================

def test_rec_01_database_failure(
    monkeypatch,
):
    """
    REC-01

    Simulate database transaction failure
    after successful inference.

    Expected API response:

        HTTP 500
        DATABASE_ERROR
    """

    # ========================================================
    # Fake YOLO box
    # ========================================================

    class FakeBox:

        def __init__(self):

            import numpy as np

            self.cls = np.array(
                [2]
            )

            self.conf = np.array(
                [0.95]
            )

            self.xyxy = np.array(
                [
                    [
                        100,
                        100,
                        500,
                        500,
                    ]
                ]
            )

    # ========================================================
    # Fake YOLO boxes
    # ========================================================

    class FakeBoxes:

        def __iter__(self):

            return iter(
                [
                    FakeBox()
                ]
            )

    # ========================================================
    # Fake result
    # ========================================================

    class FakeResult:

        def __init__(self):

            self.boxes = FakeBoxes()

        def plot(self):

            import numpy as np

            return np.zeros(
                (
                    1080,
                    1920,
                    3,
                ),
                dtype=np.uint8,
            )

    # ========================================================
    # Fake model
    # ========================================================

    class FakeModel:

        names = {
            0: "dogear-belt",
            1: "good-belt",
            2: "splice-belt",
        }

        def predict(
            self,
            source,
            conf,
            verbose,
        ):

            return [
                FakeResult()
            ]

    fake_model = FakeModel()

    # ========================================================
    # Model manager
    # ========================================================

    monkeypatch.setattr(
        main_module.model_manager,
        "get_model",
        lambda: fake_model,
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "is_ready",
        lambda: True,
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "model_name",
        "YOLO11",
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "model_version",
        "FAULT-RECOVERY",
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "confidence",
        0.5,
    )

    # ========================================================
    # Model registry
    # ========================================================

    monkeypatch.setattr(
        main_module.repository,
        "get_model_version",
        lambda **kwargs: {
            "model_id": 2,
            "model_name": "YOLO11",
            "model_version": "FAULT-RECOVERY",
        },
    )

    # ========================================================
    # Force database transaction failure
    # ========================================================

    def fake_begin():

        raise SQLAlchemyError(
            "RECOVERY_AUDIT_DATABASE_FAILURE"
        )

    monkeypatch.setattr(
        main_module.repository,
        "begin",
        fake_begin,
    )

    # ========================================================
    # Request
    # ========================================================

    response = post_detect()

    # ========================================================
    # Validate HTTP
    # ========================================================

    assert (
        response.status_code
        == 500
    ), response.text

    data = response.json()

    assert (
        data["status"]
        == "error"
    )

    assert (
        data["code"]
        == "DATABASE_ERROR"
    )

    assert (
        "request_id"
        in data
    )


# ============================================================
# REC-02
# IMAGE STATUS MUST NOT REMAIN PROCESSING
# ============================================================

def test_rec_02_image_status_after_database_failure(
    monkeypatch,
):
    """
    REC-02

    Verify that an image created before
    transaction failure does not remain PROCESSING.
    """

    # ========================================================
    # Track image_id
    # ========================================================

    created_image_ids = []

    original_create = (
        main_module.repository
        .create_image
    )

    def tracking_create_image(
        **kwargs
    ):

        image_id = original_create(
            **kwargs
        )

        created_image_ids.append(
            image_id
        )

        return image_id

    monkeypatch.setattr(
        main_module.repository,
        "create_image",
        tracking_create_image,
    )

    # ========================================================
    # Fake model
    # ========================================================

    class FakeBox:

        def __init__(self):

            import numpy as np

            self.cls = np.array(
                [2]
            )

            self.conf = np.array(
                [0.95]
            )

            self.xyxy = np.array(
                [
                    [
                        100,
                        100,
                        500,
                        500,
                    ]
                ]
            )

    class FakeBoxes:

        def __iter__(self):

            return iter(
                [
                    FakeBox()
                ]
            )

    class FakeResult:

        def __init__(self):

            self.boxes = FakeBoxes()

        def plot(self):

            import numpy as np

            return np.zeros(
                (
                    1080,
                    1920,
                    3,
                ),
                dtype=np.uint8,
            )

    class FakeModel:

        names = {
            0: "dogear-belt",
            1: "good-belt",
            2: "splice-belt",
        }

        def predict(
            self,
            source,
            conf,
            verbose,
        ):

            return [
                FakeResult()
            ]

    fake_model = FakeModel()

    # ========================================================
    # Model manager
    # ========================================================

    monkeypatch.setattr(
        main_module.model_manager,
        "get_model",
        lambda: fake_model,
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "is_ready",
        lambda: True,
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "model_name",
        "YOLO11",
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "model_version",
        "FAULT-RECOVERY",
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "confidence",
        0.5,
    )

    # ========================================================
    # Registry
    # ========================================================

    monkeypatch.setattr(
        main_module.repository,
        "get_model_version",
        lambda **kwargs: {
            "model_id": 2,
            "model_name": "YOLO11",
            "model_version": "FAULT-RECOVERY",
        },
    )

    # ========================================================
    # Database failure
    # ========================================================

    def fake_begin():

        raise SQLAlchemyError(
            "RECOVERY_AUDIT_FAILURE"
        )

    monkeypatch.setattr(
        main_module.repository,
        "begin",
        fake_begin,
    )

    # ========================================================
    # Request
    # ========================================================

    response = post_detect()

    assert (
        response.status_code
        == 500
    )

    # ========================================================
    # Must have created image
    # ========================================================

    assert len(
        created_image_ids
    ) == 1

    image_id = (
        created_image_ids[0]
    )

    # ========================================================
    # Read DB
    # ========================================================

    image_record = get_image_record(
        image_id
    )

    assert image_record is not None

    # ========================================================
    # IMPORTANT
    #
    # Production code should recover to ERROR.
    # ========================================================

    assert (
        image_record["status"]
        == "ERROR"
    ), (
        f"Image {image_id} "
        f"remained in status "
        f"{image_record['status']}"
    )

    cleanup_image_files(
        image_id
    )


# ============================================================
# REC-03
# DETECTION MUST NOT EXIST AFTER ROLLBACK
# ============================================================

def test_rec_03_no_detection_after_rollback(
    monkeypatch,
):
    """
    REC-03

    Database transaction failure must not leave
    detection records behind.
    """

    created_image_ids = []

    original_create = (
        main_module.repository
        .create_image
    )

    def tracking_create(
        **kwargs
    ):

        image_id = original_create(
            **kwargs
        )

        created_image_ids.append(
            image_id
        )

        return image_id

    monkeypatch.setattr(
        main_module.repository,
        "create_image",
        tracking_create,
    )

    # ========================================================
    # Fake model
    # ========================================================

    class FakeBox:

        def __init__(self):

            import numpy as np

            self.cls = np.array(
                [2]
            )

            self.conf = np.array(
                [0.95]
            )

            self.xyxy = np.array(
                [
                    [
                        100,
                        100,
                        500,
                        500,
                    ]
                ]
            )

    class FakeBoxes:

        def __iter__(self):

            return iter(
                [
                    FakeBox()
                ]
            )

    class FakeResult:

        def __init__(self):

            self.boxes = FakeBoxes()

        def plot(self):

            import numpy as np

            return np.zeros(
                (
                    1080,
                    1920,
                    3,
                ),
                dtype=np.uint8,
            )

    class FakeModel:

        names = {
            0: "dogear-belt",
            1: "good-belt",
            2: "splice-belt",
        }

        def predict(
            self,
            source,
            conf,
            verbose,
        ):

            return [
                FakeResult()
            ]

    fake_model = FakeModel()

    # ========================================================
    # Model
    # ========================================================

    monkeypatch.setattr(
        main_module.model_manager,
        "get_model",
        lambda: fake_model,
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "is_ready",
        lambda: True,
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "model_name",
        "YOLO11",
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "model_version",
        "FAULT-RECOVERY",
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "confidence",
        0.5,
    )

    # ========================================================
    # Registry
    # ========================================================

    monkeypatch.setattr(
        main_module.repository,
        "get_model_version",
        lambda **kwargs: {
            "model_id": 2,
            "model_name": "YOLO11",
            "model_version": "FAULT-RECOVERY",
        },
    )

    # ========================================================
    # Force transaction failure
    # ========================================================

    def fake_begin():

        raise SQLAlchemyError(
            "ROLLBACK_TEST_FAILURE"
        )

    monkeypatch.setattr(
        main_module.repository,
        "begin",
        fake_begin,
    )

    # ========================================================
    # Request
    # ========================================================

    response = post_detect()

    assert (
        response.status_code
        == 500
    )

    assert len(
        created_image_ids
    ) == 1

    image_id = (
        created_image_ids[0]
    )

    # ========================================================
    # Detection must not exist
    # ========================================================

    detection_count = count_detections(
        image_id
    )

    assert (
        detection_count
        == 0
    ), (
        f"Found {detection_count} "
        f"detection(s) after rollback"
    )

    # ========================================================
    # Inspection must not exist
    # ========================================================

    inspection_count = (
        count_inspection_results(
            image_id
        )
    )

    assert (
        inspection_count
        == 0
    ), (
        "Inspection result exists "
        "after failed transaction"
    )

    cleanup_image_files(
        image_id
    )


# ============================================================
# REC-04
# ORPHAN FILE AUDIT
# ============================================================

def test_rec_04_orphan_file_audit(
    monkeypatch,
):
    """
    REC-04

    Detect whether original/result files remain
    after a database transaction failure.

    This is intentionally an AUDIT.

    If files remain, the test reports the orphan
    condition clearly instead of hiding it.
    """

    created_image_ids = []

    original_create = (
        main_module.repository
        .create_image
    )

    def tracking_create(
        **kwargs
    ):

        image_id = original_create(
            **kwargs
        )

        created_image_ids.append(
            image_id
        )

        return image_id

    monkeypatch.setattr(
        main_module.repository,
        "create_image",
        tracking_create,
    )

    # ========================================================
    # Fake model
    # ========================================================

    class FakeBox:

        def __init__(self):

            import numpy as np

            self.cls = np.array(
                [2]
            )

            self.conf = np.array(
                [0.95]
            )

            self.xyxy = np.array(
                [
                    [
                        100,
                        100,
                        500,
                        500,
                    ]
                ]
            )

    class FakeBoxes:

        def __iter__(self):

            return iter(
                [
                    FakeBox()
                ]
            )

    class FakeResult:

        def __init__(self):

            self.boxes = FakeBoxes()

        def plot(self):

            import numpy as np

            return np.zeros(
                (
                    1080,
                    1920,
                    3,
                ),
                dtype=np.uint8,
            )

    class FakeModel:

        names = {
            0: "dogear-belt",
            1: "good-belt",
            2: "splice-belt",
        }

        def predict(
            self,
            source,
            conf,
            verbose,
        ):

            return [
                FakeResult()
            ]

    fake_model = FakeModel()

    # ========================================================
    # Model
    # ========================================================

    monkeypatch.setattr(
        main_module.model_manager,
        "get_model",
        lambda: fake_model,
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "is_ready",
        lambda: True,
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "model_name",
        "YOLO11",
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "model_version",
        "FAULT-RECOVERY",
    )

    monkeypatch.setattr(
        main_module.model_manager,
        "confidence",
        0.5,
    )

    # ========================================================
    # Registry
    # ========================================================

    monkeypatch.setattr(
        main_module.repository,
        "get_model_version",
        lambda **kwargs: {
            "model_id": 2,
            "model_name": "YOLO11",
            "model_version": "FAULT-RECOVERY",
        },
    )

    # ========================================================
    # Force transaction failure
    # ========================================================

    def fake_begin():

        raise SQLAlchemyError(
            "ORPHAN_FILE_TEST_FAILURE"
        )

    monkeypatch.setattr(
        main_module.repository,
        "begin",
        fake_begin,
    )

    # ========================================================
    # Request
    # ========================================================

    response = post_detect()

    assert (
        response.status_code
        == 500
    )

    assert len(
        created_image_ids
    ) == 1

    image_id = (
        created_image_ids[0]
    )

    # ========================================================
    # Find files
    # ========================================================

    original_files, result_files = (
        find_files_for_image(
            image_id
        )
    )

    # ========================================================
    # Report audit result
    # ========================================================

    print(
        "\n"
        + "=" * 60
    )

    print(
        "REC-04 ORPHAN FILE AUDIT"
    )

    print(
        "=" * 60
    )

    print(
        f"Image ID      : {image_id}"
    )

    print(
        "Original files:"
    )

    for file_path in original_files:

        print(
            f"  - {file_path}"
        )

    print(
        "Result files:"
    )

    for file_path in result_files:

        print(
            f"  - {file_path}"
        )

    print(
        "=" * 60
    )

    # ========================================================
    # CURRENT SYSTEM BEHAVIOR
    #
    # The current main.py does not explicitly delete
    # files after database transaction failure.
    #
    # Therefore this audit is expected to expose
    # orphan files if they remain.
    # ========================================================

    orphan_files = (
        original_files
        + result_files
    )

    if orphan_files:

        print(
            "WARNING: ORPHAN FILES DETECTED"
        )

        print(
            f"Count: {len(orphan_files)}"
        )

    else:

        print(
            "No orphan files detected"
        )

    print(
        "=" * 60
    )

    # ========================================================
    # Cleanup audit files
    # ========================================================

    cleanup_image_files(
        image_id
    )

    # Audit itself passes because the purpose is
    # to detect/report the condition.
    assert True


# ============================================================
# REC-05
# RECOVERY SUMMARY
# ============================================================

def test_recovery_audit_summary():
    """
    REC-05

    Recovery audit summary marker.
    """

    assert True